export const FETCH_QUESTIONS_STARTED = 'FETCH_QUESTIONS_STARTED';
export const FETCH_QUESTIONS_LOADED = 'FETCH_QUESTIONS_LOADED';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';
export const QUESTION_ANSWERED_CORRECTLY = 'QUESTION_ANSWERED_CORRECTLY';
export const QUESTIONS_CHANGED = 'QUESTIONS_CHANGED';
export const GAME_OVER = 'GAME_OVER';
